### ISSUE TITLE
Random number generator misses the right boundary

### ISSUE THREAD

**Issue by rottenworld** [ssast-tech/lottery-2021#1]
```javascript

function randBetween (a, b) {
 return Math.random() * (b - a) + a
}
```
Here, should (b - a + 1) rather than (b - a) be multipled? 
In fact, the last element of `LanguageToStringMapping`——namely `SQL`, was not chosen in any round.

**Comment by panda2134** [comment]
Thanks for your issue. This is indeed an error, and has already been fixed. I feel very sorry for the mistake.
